In [10]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Analytics and Statistics using Python
## L10:NumPy


<img src='../../prasami_images/prasami_color_tutorials_small.png' width='400' alt="By Pramod Sharma : pramod.sharma@prasami.com" align = "left"/>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
X = np.array([[0,1,2,3,4],[5,6,7,8,9]])
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
X.dtype

dtype('int64')

In [8]:
X = np.arange(10).reshape((2,5))
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
num = [0,1,2,3,4,5]
type(num)

list

In [13]:
np_from_lst = np.array(num, dtype =np.float64)
display(type(np_from_lst))
np_from_lst

numpy.ndarray

array([0., 1., 2., 3., 4., 5.])

In [15]:
lst_2d = [[1,2,3], [4,5,6], [7,8,9]]
lst_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
ary_2d = np.array(lst_2d, dtype=np.float16)
ary_2d


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)

In [22]:
ary_2d.dtype, type(ary_2d)

(dtype('float16'), numpy.ndarray)

In [25]:
ary_2d.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [29]:
X1 = np.array([[[0,1,2,3,4],[5,6,7,8,9]],
               [['a', 'b','c','d','e'], 
               ['f','g','h','i', 'j']]])
X1

array([[['0', '1', '2', '3', '4'],
        ['5', '6', '7', '8', '9']],

       [['a', 'b', 'c', 'd', 'e'],
        ['f', 'g', 'h', 'i', 'j']]], dtype='<U21')

In [30]:
X1.shape

(2, 2, 5)

In [34]:
X1.ndim

3

In [35]:
X2 = np.array([[[0,1,2,3,4],[5,6,7,8,9]],
               [list('abcde'), list('fghij')]])
X2

array([[['0', '1', '2', '3', '4'],
        ['5', '6', '7', '8', '9']],

       [['a', 'b', 'c', 'd', 'e'],
        ['f', 'g', 'h', 'i', 'j']]], dtype='<U21')

In [36]:
X2[0]

array([['0', '1', '2', '3', '4'],
       ['5', '6', '7', '8', '9']], dtype='<U21')

In [37]:
X2[:,1]

array([['5', '6', '7', '8', '9'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U21')

In [38]:
X2[:,:, 1]

array([['1', '6'],
       ['b', 'g']], dtype='<U21')

In [41]:
X.dtype.name, X1.dtype.name, X2.dtype.name

('int64', 'str672', 'str672')

In [44]:
Y = np.ndarray(( 2,3,4), dtype = np.float32)
Y

array([[[7.803875e-37, 3.484048e-41, 0.000000e+00, 0.000000e+00],
        [6.305843e-44, 6.866362e-44, 6.726233e-44, 6.305843e-44],
        [6.726233e-44, 7.146622e-44, 1.177091e-43, 6.866362e-44]],

       [[7.006492e-44, 8.127531e-44, 7.286752e-44, 7.987401e-44],
        [8.127531e-44, 7.006492e-44, 6.726233e-44, 6.445973e-44],
        [7.006492e-44, 7.426882e-44, 7.847271e-44, 1.261169e-43]]],
      dtype=float32)

In [45]:
boo_arr = np.array([-3,-2,-1,0,1,2,3], dtype = np.bool_)
boo_arr

array([ True,  True,  True, False,  True,  True,  True])

In [47]:
np.array([0,1,2,3]).astype(np.int8).astype('str')

array(['0', '1', '2', '3'], dtype='<U4')

In [48]:
X.size

10

Absolute Max Min Values

In [49]:
for dtp in [np.int8, np.int16, np.int32, np.int64]:
    
    print (f'''for {dtp}:
           - min value: {np.iinfo(dtp).min}
           - max value: {np.iinfo(dtp).max}
''')

for <class 'numpy.int8'>:
           - min value: -128
           - max value: 127

for <class 'numpy.int16'>:
           - min value: -32768
           - max value: 32767

for <class 'numpy.int32'>:
           - min value: -2147483648
           - max value: 2147483647

for <class 'numpy.int64'>:
           - min value: -9223372036854775808
           - max value: 9223372036854775807



In [50]:
for dtp in [np.float16, np.float32, np.float64]:
    
    print (f'''for {dtp}:
           - min value    : {np.finfo(dtp).min}
           - max value    : {np.finfo(dtp).max}
           - epsilon value: {np.finfo(dtp).eps}
''')

for <class 'numpy.float16'>:
           - min value    : -65504.0
           - max value    : 65504.0
           - epsilon value: 0.0009765625

for <class 'numpy.float32'>:
           - min value    : -3.4028234663852886e+38
           - max value    : 3.4028234663852886e+38
           - epsilon value: 1.1920928955078125e-07

for <class 'numpy.float64'>:
           - min value    : -1.7976931348623157e+308
           - max value    : 1.7976931348623157e+308
           - epsilon value: 2.220446049250313e-16



In [53]:
ary_2d[0:2, 0:2]

array([[1., 2.],
       [4., 5.]], dtype=float16)

In [54]:
ary_2d[::-1, ::-1]

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]], dtype=float16)

In [58]:
ary_2d[1,1] = 999
ary_2d

array([[  1.,   2.,   3.],
       [  4., 999.,   6.],
       [  7.,   8.,   9.]], dtype=float16)

In [61]:
ary_zeros = np.zeros((3,3), dtype=np.int16, order = 'C')
ary_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [64]:
ary_ones = np.ones((3,3), dtype=np.int16, order = 'C')
ary_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [65]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
Z = np.random.random((4,4))
Z

array([[0.02309766, 0.08880179, 0.64724394, 0.55358621],
       [0.57843983, 0.75374937, 0.69442957, 0.10859773],
       [0.48359916, 0.57186582, 0.11471962, 0.43221793],
       [0.81189776, 0.84805553, 0.77592251, 0.31524993]])

In [74]:
Z.min(axis = 0), Z.max(axis = 0), Z.mean(axis = 0)

(array([0.02309766, 0.08880179, 0.11471962, 0.10859773]),
 array([0.81189776, 0.84805553, 0.77592251, 0.55358621]),
 array([0.4742586 , 0.56561813, 0.55807891, 0.35241295]))

In [79]:
Z.min(axis = 0, keepdims=True)

array([[0.02309766, 0.08880179, 0.11471962, 0.10859773]])

In [84]:
X2 = np.array([20,30,40,50])
y = np.arange(4)
display(X2, y)

array([20, 30, 40, 50])

array([0, 1, 2, 3])

In [85]:
X2+y

array([20, 31, 42, 53])

In [86]:
X2-y

array([20, 29, 38, 47])

In [87]:
y**2

array([0, 1, 4, 9])

In [88]:
X2 < 35

array([ True,  True, False, False])