### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [1]:

import numpy as np
np.__version__


'2.1.2'

### 2. Write a NumPy program to get help on the add function.

In [2]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\priyanka\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
  

### 3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [3]:

x = np.array([1,2,3,4,5,6])
a = np.all(x) 
a

np.True_

### 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:

x = np.array([1,0,3,4,5,6])
b = np.all(x)
b 


np.False_

### 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [5]:

arr = np.array([1.0, 2.0, np.inf, -np.inf, np.nan, 5.0])
np.isfinite(arr)
 

array([ True,  True, False, False, False,  True])

### 6. Write a NumPy program to test element-wise for positive or negative infinity

In [6]:

arr = np.array([1.0, 2.0, np.inf, -np.inf, np.nan, 5.0])
np.isinf(arr)

array([False, False,  True,  True, False, False])

### 7. Write a NumPy program to test element-wise for NaN of a given array.

In [7]:

np.isnan(arr)

array([False, False, False, False,  True, False])

### 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [8]:


arr1 = np.array([1.0, -1.0, 2 + 3j, 4.0, np.nan, 5.0]) 
display(np.iscomplexobj(arr1))

display(np.isreal(arr1))

display(np.isscalar(arr1))



True

array([ True,  True, False,  True,  True,  True])

False

### 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [9]:


arr_1 = np.array([1,3,3,4,5])
arr_2 = np.array([3,3,1,2,1])

greater = arr_1 > arr_2
greater_equal = arr_1 >= arr_2
less = arr_1 < arr_2
less_equal = arr_1 <= arr_2

print("Array 1:", arr_1)
print("Array 2:", arr_2)
print("Greater :", greater)
print("Greater or Equal :", greater_equal)
print("Less :", less)
print("Less or Equal :", less_equal)

Array 1: [1 3 3 4 5]
Array 2: [3 3 1 2 1]
Greater : [False False  True  True  True]
Greater or Equal : [False  True  True  True  True]
Less : [ True False False False False]
Less or Equal : [ True  True False False False]


### 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [10]:
ar = np.array([1, 7, 13, 105])
size = ar.nbytes
display(size)

32

### 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [11]:

a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)

# Output the results
print("Array of 10 zeros:", a)
print("Array of 10 ones:", b)
print("Array of 10 fives:",c)


Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


### 12. Write a NumPy program to create an array of the integers from 30 to70.

In [12]:
a1 = np.arange(30,71)
print(a1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### 13. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [13]:
a2 = np.arange(30,71,2)
print(a2)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### 14. Write a NumPy program to create a 3x3 identity matrix.

In [14]:
arr12 = np.array ([[1,2,3],
         [3,4,5],
         [6,7,8]])
arr12

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

### 15. Write a NumPy program to generate a random number between 0 and 1.

In [15]:
Z = np.random.random((0,1))
print(Z)

[]


### 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [16]:
ZA = np.random.randn(15) #15 random numbers from std normal distribution
print(ZA)

[ 0.97851862 -0.67923906  1.57371204  0.26353974 -1.12226092 -0.53529354
  2.56929676  1.00862252  0.40985925  1.75697921 -0.61786205  0.4076759
 -1.36522883 -0.33598145  0.34160721]


### 17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [17]:
vector = np.arange(15,56) #vector from 15 to 55

print(vector[1:-1]) #skip 1st and last element

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### 18. Write a NumPy program to create a 3X4 array

In [19]:
arr4 =np.array([[1,2,3,4],
         [3,4,5,6],
         [6,7,8,9]])
arr4


array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

### 19.Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [37]:
vector1 = np.linspace(5,50,10)
print(vector1)


[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


### 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [39]:
vector3 =np.arange(21)

# Change the sign of the numbers in the range from 9 to 15
vector[(vector >= 9) & (vector <= 15)] *= -1

print(vector3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [40]:

# Create a vector of length 5 filled with arbitrary integers from 0 to 10
v = np.random.randint(0, 11, size=5)

print(v)


[ 2 10  9  8  2]


### 22. Write a NumPy program to multiply the values of two given vectors.

In [41]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

result = v1 * v2
print("Result Of multiplication", result)

Result Of multiplication [ 4 10 18]


### 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [42]:
matrix = np.arange(10,22).reshape(3,4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### 24. Write a NumPy program to find the number of rows and columns of a given matrix.

In [44]:
matrix.shape

(3, 4)

### 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [45]:
#Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [47]:
m1 = np.zeros((10,10))

m1[0, :]=1
m1[-1,:]=1
m1[:,0]=1
m1[:,-1]=1

print(m1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,3, 4, 5.

In [48]:
# Create a 5x5 zero matrix
zero_matrix = np.zeros((5, 5))

# Set the elements on the main diagonal
diagonal_values = np.array([1, 2, 3, 4, 5])
np.fill_diagonal(zero_matrix, diagonal_values)

print(zero_matrix)



[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [49]:
# Create a 3x3x3 array filled with random values
array_3x3x3 = np.random.random((3, 3, 3))

print(array_3x3x3)


[[[0.24895989 0.14779014 0.71898519]
  [0.77278303 0.68966874 0.44635876]
  [0.84885346 0.78823447 0.89334583]]

 [[0.39465313 0.24925841 0.20424343]
  [0.3187566  0.94956812 0.77940317]
  [0.24674719 0.02416279 0.11022027]]

 [[0.21474348 0.96398351 0.05225576]
  [0.02987895 0.58580138 0.07172152]
  [0.3648812  0.95206268 0.38735253]]]


### 29. Write a NumPy program to compute the inner product of two given vectors.

In [50]:
# Define two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Compute the inner product
inner_product = np.dot(vector_a, vector_b)
# Alternatively, you can use:
# inner_product = vector_a @ vector_b

print("Inner Product:", inner_product)

Inner Product: 32


### 30. Write a NumPy program to sort a given array by row and column in ascending order.

In [ ]:
# Create a sample array
array = np.array([[3, 1, 2],
                  [9, 7, 6],
                  [5, 8, 4]])

# Sort the array by rows
sorted_by_rows = np.sort(array, axis=1)

# Sort the array by columns
sorted_by_columns = np.sort(array, axis=0)

print("\nSorted by Rows:")
print(sorted_by_rows)

print("\nSorted by Columns:")
print(sorted_by_columns)


### 31. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [52]:
#Create a sample array
array = np.array([11, 30, 80, 50, 60, 87, 81, 89, 90])

# Specify the number
specified_number = 45

# Extract numbers less than the specified number
less_than = array[array < specified_number]

# Extract numbers greater than the specified number
greater_than = array[array > specified_number]


print(f"\nNumbers less than {specified_number}:")
print(less_than)

print(f"\nNumbers greater than {specified_number}:")
print(greater_than)


Numbers less than 45:
[11 30]

Numbers greater than 45:
[80 50 60 87 81 89 90]


### 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.

In [53]:
array = np.array([10, 22, 35, 42, 30, 40, 50, 100, 70])

# Specify the number
specified_number = 45

# Replace numbers equal to the specified number
array[array == specified_number] = -1  # Replace equal to specified_number with -1

# Replace numbers less than the specified number
array[array < specified_number] = 0  # Replace less than specified_number with 0

# Replace numbers greater than the specified number
array[array > specified_number] = 100  # Replace greater than specified_number with 100

print("Modified Array:")
print(array)

Modified Array:
[  0   0   0   0 100 100 100 100 100]


### 33. Write a NumPy program to create an array of equal shape and data type of a given array.

In [1]:
import numpy as np

# Create a sample array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of the same shape and data type using np.empty_like
empty_array = np.empty_like(original_array)

# Create an array of the same shape and data type using np.zeros_like
zero_array = np.zeros_like(original_array)

print("Original Array:")
print(original_array)

print("\nEmpty Array of the same shape and type:")
print(empty_array)

print("\nZero Array of the same shape and type:")
print(zero_array)

Original Array:
[[1 2 3]
 [4 5 6]]

Empty Array of the same shape and type:
[[94870406885326              0              0]
 [             0              0              0]]

Zero Array of the same shape and type:
[[0 0 0]
 [0 0 0]]


### 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [2]:
# Create a three-dimensional array with shape (3, 5, 4)
three_d_array = np.random.rand(3, 5, 4)
print("Three-dimensional array with shape (3, 5, 4):")
print(three_d_array)


Three-dimensional array with shape (3, 5, 4):
[[[5.95222500e-01 1.90046473e-01 9.86286698e-01 2.41141832e-01]
  [8.12820525e-01 8.70670801e-01 4.12281369e-01 5.34277727e-01]
  [7.18464061e-01 7.01913967e-01 3.60227958e-01 9.05764219e-01]
  [8.13824150e-01 5.85175599e-01 9.64541729e-01 1.13423925e-01]
  [7.41909358e-02 1.46345322e-01 4.18556412e-01 9.51178055e-01]]

 [[5.54290789e-01 4.50762569e-02 6.45685405e-01 5.63617252e-02]
  [6.07695957e-04 2.12711050e-01 2.90827557e-01 9.84750274e-01]
  [9.23203073e-01 6.86481196e-01 9.81763815e-03 3.56940381e-01]
  [5.46115608e-01 7.84320544e-01 4.39032631e-01 4.23316690e-01]
  [4.86504778e-02 6.91979325e-01 2.17689434e-01 6.88468419e-01]]

 [[4.49157766e-02 8.12174963e-01 1.02448894e-01 5.48353198e-02]
  [6.73535874e-01 5.17766056e-01 2.94906512e-01 3.44099194e-01]
  [3.60940140e-01 6.88760374e-01 3.57563278e-01 6.80308656e-01]
  [8.99904285e-01 9.50776930e-01 1.74300480e-02 8.16462561e-03]
  [4.51492554e-01 6.63317531e-01 8.35962364e-01 5.9859

### 35. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [3]:
import numpy as np

# Define two arrays of the same size
array1 = np.array([2, 5, 3, 4])
array2 = np.array([4, 8, 6, 8])

# Check if the arrays are of the same size
if array1.shape == array2.shape:
    # Multiply the arrays element-by-element
    result = array1 * array2
    print("Result of element-wise multiplication:", result)
else:
    print("Error: Arrays must be of the same size.")

Result of element-wise multiplication: [ 5 12 21 32]
