In [2]:
import numpy as np
np.__version__

'2.1.1'

In [3]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            ~/.local/lib/python3.10/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array w

In [5]:
x = np.array([2,3,4,5])
a = np.all(x) #to check none of all elements is zero
a

np.True_

In [8]:
x = np.array([1234,3456,3455,0])
b = np.all(x)
b

np.False_

In [10]:
arr = np.array([1.0,2.0,5.0,np.nan,5.0])
np.isfinite(arr)

array([ True,  True,  True, False,  True])

In [11]:
arr = np.array([1.0,2.0,3.0,np.nan,np.inf,5.0])
np.isinf(arr)

array([False, False, False, False,  True, False])

In [12]:
np.isnan(arr)

array([False, False, False,  True, False, False])

In [14]:
arr1 = np.array([1,2,3+3j,np.nan,5.0])
display(np.iscomplexobj(arr1))
display(np.isreal(arr1))
display(np.isscalar(arr1))

True

array([ True,  True, False,  True,  True])

False

In [18]:
arr2 = np.array([100,200,300,500,60])
arr3 = np.array([300,30,50,20,10])

greater = arr2 > arr3
gre_equal = arr2 >= arr3
less = arr2 < arr3
less_equal = arr2 <= arr3

print(arr2)
print(arr3)
print("greater:",greater)
print("gre_equal",gre_equal)
print("less",less)
print("less_equal",less_equal)

[100 200 300 500  60]
[300  30  50  20  10]
greater: [False  True  True  True  True]
gre_equal [False  True  True  True  True]
less [ True False False False False]
less_equal [ True False False False False]


In [20]:
arrays = np.array([1,7,13,105])
size = arrays.nbytes #memeory size calculted by nbytes
display(size)

32

In [23]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [24]:
ar2 = np.arange(30,71)
ar2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [25]:
ar2 = np.arange(30,71,2)
ar2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [29]:
a1 = np.array([[1,2,3],[4,5,6],[6,7,8]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [31]:
a= np.random.random((0,1))
print(a)

[]


In [34]:
b= np.random.randn((15))
print(b)

[-0.42046453 -1.06870136 -0.42703235  0.19731204  1.26935228  0.24490378
 -0.78037478  1.52158784  0.30999705 -0.19540669  0.5697871  -1.42461057
  0.02944452  0.39536164 -0.09656725]


In [36]:
vector = np.arange(15,56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [38]:
a = np.array([[1,2,3,4],
              [2,4,6,7],
              [1,3,4,5]])
a

array([[1, 2, 3, 4],
       [2, 4, 6, 7],
       [1, 3, 4, 5]])

In [41]:
vc = np.linspace(5,50,10)
print(vc)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [44]:
vc1 = np.arange(21)

vc1[(vc1>=9) & (vc1<=15)] *=-1
print(vc1)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [45]:
v = np.random.randint(0,11,size=5)
print(v)

[ 0  2  6  7 10]


In [46]:
v1 = np.array([1,2,3])
v2 = np.array([6,8,9])

result = v1 * v2
print(result)

[ 6 16 27]


In [47]:
matrix = np.arange(10,22).reshape(3,4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [48]:
matrix.shape

(3, 4)

In [49]:
i_m = np.eye(3)
print(i_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
m1 = np.zeros((10,10))

m1[0,:]=1
m1[-1,:]=1
m1[:,0]=1
m1[:,-1]=1

print(m1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [53]:
zero_matrix = np.zeros((5,5))

dg_values = np.array([1,2,3,4,5])
np.fill_diagonal(zero_matrix,dg_values)
print(zero_matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [56]:
array1= np.random.random((3,3,3))
print(array1)

[[[0.29401863 0.14640688 0.88532158]
  [0.13671885 0.09562438 0.77251077]
  [0.55648463 0.14077511 0.94553431]]

 [[0.96060528 0.5907328  0.81048968]
  [0.32139406 0.80935786 0.41431781]
  [0.1817799  0.37135571 0.36376854]]

 [[0.79273547 0.87574168 0.70024991]
  [0.42741744 0.94854836 0.33108688]
  [0.83839985 0.11838115 0.56127459]]]


In [57]:
va=np.array([1,4,3])
vb=np.array([2,3,4])
inner_product = np.dot(va,vb)
print("inner product:",inner_product)

inner product: 26


In [58]:
array = np.array([[3,1,2],
                  [1,2,3],
                  [4,5,6]])

sorted_by_rows = np.sort(array, axis=1)

sorted_by_columns = np.sort(array, axis=0)

print("\nsorted by rows:")
print(sorted_by_rows)

print("\nsorted by columns:")
print(sorted_by_columns)


sorted by rows:
[[1 2 3]
 [1 2 3]
 [4 5 6]]

sorted by columns:
[[1 1 2]
 [3 2 3]
 [4 5 6]]


In [59]:
ab = np.array([12,24,34,46,65,60,77])

specified_number = 25
less_than =ab[ab < specified_number]
greater_than = ab[ab> specified_number]

print(f"\nNumbers less than{specified_number}:")
print(less_than)
print(f"\nNumbers greater than{specified_number}")
print(greater_than)


Numbers less than25:
[12 24]

Numbers greater than25
[34 46 65 60 77]


In [66]:
ac = np.array([10,20,45,40,409,60,44,200])

specified_number = 45
ac[ac==specified_number]=-1
ac[ac<specified_number]=0
ac[ac>specified_number]=100
print("modified array:")
print(ac)

modified array:
[  0   0   0   0 100 100   0 100]


In [67]:
import numpy as np 
og_array = np.array([[1,2,3],[4,5,6]])
em_array =np.empty_like(og_array)
zero_array = np.zeros_like(og_array)

print("original array:")
print(og_array)

print("\nempty array of the same shape and type")
print(em_array)

print("\nZero array of the same shape and type:")
print(zero_array)

original array:
[[1 2 3]
 [4 5 6]]

empty array of the same shape and type
[[94521816478871              0              0]
 [             0              0              0]]

Zero array of the same shape and type:
[[0 0 0]
 [0 0 0]]


In [68]:
a_3=np.random.rand(3,5,4)
print("three dimensional with shape(3,4,5):")
print(a_3)

three dimensional with shape(3,4,5):
[[[9.80329320e-01 2.55098610e-01 1.50141187e-02 2.63745943e-02]
  [8.67595995e-01 7.19975287e-01 7.99096100e-01 9.75486521e-01]
  [7.54752407e-01 8.14411177e-01 3.18917538e-01 8.03706112e-01]
  [5.38553859e-01 4.06691426e-01 4.67125606e-01 3.60359881e-01]
  [5.01373224e-02 2.80356184e-01 8.09455203e-01 1.03287579e-01]]

 [[5.45653189e-01 8.92659170e-01 6.86418686e-01 7.54512598e-01]
  [1.03549737e-01 3.37050631e-01 9.70926417e-01 8.90600573e-02]
  [4.99620210e-01 3.08983223e-01 4.58766412e-01 2.97195569e-04]
  [7.60463843e-01 4.96554064e-01 6.85258498e-01 4.41556259e-01]
  [4.94707648e-01 4.85114784e-02 5.29461674e-01 6.51490976e-01]]

 [[4.61651303e-01 7.18959008e-01 9.70171615e-01 4.89913189e-01]
  [5.80852274e-01 9.56270373e-01 6.95262026e-01 5.74489957e-01]
  [8.14601088e-01 2.37112628e-01 6.44839261e-01 2.28591676e-01]
  [9.35476918e-01 5.47773290e-01 1.87371917e-01 1.85941307e-01]
  [5.66702479e-01 9.35847157e-01 2.11112262e-01 3.24007087e-01]